version: '3.7'

# this is a working example for a dockerized install of about 15 low-volume mailing lists
# pgsql resides on a separate server. dnsmasq helps resolving local addresses.
# the passwords and IP addresses come from a .env file (shared by my dockerized mail environment)
#

services:


  mailman-core:
    image: maxking/mailman-core:0.4
    container_name: mailman-core
    hostname: mailman-core.${DOMAIN}.de
    volumes:
      - ${MM3_DATA_DIR}:/opt/mailman/
      - /etc/localtime:/etc/localtime:ro
    stop_grace_period: 30s
    environment:
      - TIMEZONE=Europe/Berlin
      - DATABASE_URL=${MM3_DATABASE_URL}
      - DATABASE_TYPE=postgres
      - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
      - HYPERKITTY_API_KEY=${MM3_HYPERKITTY_API_KEY}
      - SMTP_HOST=${MM3_SMTP_HOST}
      - SMTP_PORT=${MM3_SMTP_PORT}
      - SMTP_HOST_USER=${SMTP_USER}
      - SMTP_HOST_PASSWORD=${LDAP_SMTP_PASSWORD}
      - MAILMAN_REST_PASSWORD=${MM3_MAILMAN_REST_PASSWORD}
    dns:
      - ${DNSMASQ_IP}
    extra_hosts:
       - ${MM3_SMTP_HOST}:${MM3_SMTP_IP}
       - postgres-db:${MM3_POSTGRES_IP}
    networks:
      services:
        ipv4_address: ${MM3_CORE_IP}
        
        

  mailman-web:
    image: maxking/mailman-web:0.4
    container_name: mailman-web
    hostname: mailman-web
    # depends_on:
      # - postgres-db
    links:
      - mailman-core:mailman-core
    volumes:
      - ${MM3_WEB_DIR}:/opt/mailman-web-data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TIMEZONE=Europe/Berlin
      - DATABASE_TYPE=postgres
      - DATABASE_URL=${MM3_WEB_DATABASE_URL}
      - HYPERKITTY_API_KEY=${MM3_HYPERKITTY_API_KEY}
      - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${MM3_SMTP_PORT}
      - SMTP_HOST_USER=${SMTP_USER}
      - SMTP_HOST_PASSWORD=${LDAP_SMTP_PASSWORD}
      - SECRET_KEY=${MM3_HYPERKITTY_API_KEY}
      - MAILMAN_REST_PASSWORD=${MM3_MAILMAN_REST_PASSWORD}
      - SERVE_FROM_DOMAIN=elternserver.de
      - DJANGO_ALLOWED_HOSTS=${MM3_DJANGO_ALLOWED_HOSTS}
      - DJANGO_RANDOM_SECRET_KEY=${MM3_DJANGO_RANDOM_SECRET_KEY}
    
    extra_hosts:
       - ${MM3_SMTP_HOST}:${MM3_SMTP_IP}
       # - ${MM3_SMTP_HOST}:${EXIM_INT_MAILOUT_IP}
       - postgres-db:${MM3_POSTGRES_IP}
    networks:
      services:
        ipv4_address: ${MM3_WEB_IP}
    labels:

